name: ci

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-18.04 currently same as ubuntu-latest
        # TODO: windows-latest (windows server 2019) fails at pipenv install when creating virtual env
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest]
        # black doesn't seem to work with python-3.5 on ubuntu-18.04
        python: [3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev --skip-lock --python=${{ matrix.python }}
    - name: Run tests
      run: |
        pipenv run tests
    - name: Lint with black
      run: |
        pipenv run black --check .
