name: ci

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-18.04 currently same as ubuntu-latest
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]
        python: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
    # must be in it's own step, see 821eaaf and 49dd788
    # https://github.com/actions/runner/issues/258
    - name: Install python packages
      run: |
        pipenv install --verbose --dev --skip-lock --python=${{ matrix.python }}
    - name: Run tests
      run: |
        pipenv run tests
    - name: Lint with black
      run: |
        pipenv run black --check .
