name: ci

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # ubuntu-18.04 currently same as ubuntu-latest
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev 
    - name: Run tests
      run: |
        pipenv run tests
    - name: Lint with black
      run: |
        pipenv run black --check .
